name: Build smart contracts

on:
  workflow_call:
    secrets:
      PROVIDER_URL:
        required: true

    inputs:

      node-version:
        description: "NodeJS version"
        type: string
        default: 16.15.0
        required: false

      compile-command:
        description: "npm command used in compile step"
        type: string
        default: compile
        required: false

jobs:
  smart-contracts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # from tag: v3.5.0
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3

      - name: Setup node
        # from tag: v3.6.0
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version: ${{ inputs.node-version }}

      - name: Set up node_modules cache
        # from tag: v3.3.1
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install
        run: npm install

      - name: Compile
        run: npm run ${{ inputs.compile-command }}
