name: Deploy cockpit

on:
  workflow_dispatch:
    inputs:
      cockpit-app-name:
        description: 'IPOR cockpit Amplify application name'
        required: true
        default: 'ipor-dev-cockpit'
        type: choice
        options:
          - ipor-dev-cockpit
          - ipor-rinkeby-cockpit
          - ipor-goerli-cockpit

jobs:
  notify:
    uses: ./.github/workflows/notify-slack.yml
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  deploy:
    needs:
      - notify
    uses: ./.github/workflows/deploy-amplify.yml
    with:
      aws-region: eu-central-1
      app-name: ${{ github.event.inputs.cockpit-app-name }}
      branch: ${{ needs.notify.outputs.branch-name }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  report:
    if: ${{ always() }}
    needs:
      - notify
      - deploy
    uses: ./.github/workflows/report-slack.yml
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    with:
      success: ${{ needs.deploy.result == 'success' }}
      slack-status-msg-id: ${{ needs.notify.outputs.slack-status-msg-id }}
